# Site settings
title: Dragonly's Blog
email: liyilongko@gmail.com
description: "This is the first time I setup a real blog and publish on the Internet. Enjoy all the fun :)"
baseurl: ""
url: "http://liyilonggithub.github.io"
timezone: "Asia/Shanghai"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5
#lsi: true

kramdown:
  input: GFM

sass:
  sass_dir: css
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Bruce Lee"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "draft"
    values:
      layout: "draft"